### ISSUE TITLE
 Read config from environment

### ISSUE THREAD

**Issue by aesedepece** [witnet/price_feed_poller#46]
Reading configuration from the environment will be much more convenient when trying to automate deployment of chain integration stacks.

**Comment by guidiaz** [comment]
Besides, it should be possible to set the path to the JSON file containing price feeds triggering conditions as an URL.

**Comment by guidiaz** [comment]
These will be the new env vars:
```
## Path to price feeds configuration JSON file
WPFP_CONFIG_PATH="https://raw.githubusercontent.com/witnet/data-feeds-explorer/main/packages/api/src/dataFeedsRouter.json"

## Network name 
WPFP_NETWORK_NAME="chain.network"

## Network connection timeout
WPFP_NETWORK_TIMEOUT_SECS=60

## Web3 params
WPFP_WEB3_FINALIZATION_SECS=60
WPFP_WEB3_FROM=""
WPFP_WEB3_GAS=300_000
WPFP_WEB3_GAS_PRICE=30_000_000_000
WPFP_WEB3_MAX_REVERTS=3
WPFP_WEB3_PROVIDER="http://127.0.0.1:8888"
WPFP_WEB3_PROVIDER_POA=true
WPFP_WEB3_PROVIDER_WAITING_TIMEOUT_SECS=130
WPFP_WEB3_PROVIDER_POLLING_LATENCY_SECS=13
WPFP_WEB3_SYMBOL=""

## Witnet params
WPFP_WITNET_RESOLUTION_SECS=300
WPFP_WITNET_TOOLKIT_TIMEOUT_SECS=30

**Comment by guidiaz** [comment]
Generated witnet/price-feeds-poller:1.3.0 docker imaged based on draft PR:
-

**Comment by guidiaz** [comment]
Testing w/ Polygon Mumbai on portainer:
```
  poller:
    restart: unless-stopped
    image: witnet/price-feeds-poller:1.3.0
    command: "--loop_interval_secs 90"
    environment:
      PYTHONUNBUFFERED: 1
      WPFP_CONFIG_PATH: "https://raw.githubusercontent.com/witnet/data-feeds-explorer/main/packages/api/src/dataFeedsRouter.json"
      WPFP_NETWORK_NAME: "polygon.goerli"
      WPFP_WEB3_FINALIZATION_SECS: 20
      WPFP_WEB3_FROM: "0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B"
      WPFP_WEB3_PROVIDER: "http://gateway:8535"
      WPFP_WEB3_PROVIDER_POA: "true"
      WPFP_WEB3_PROVIDER_WAITING_TIMEOUT_SECS: 120
      WPFP_WEB3_PROVIDER_POLLING_LATENCY_SECS: 2
      WPFP_WEB3_SYMBOL: "MATIC"
    depends_on:
      - gateway
    links:
      - gateway
```
